services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paloma_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
